### ISSUE TITLE
CloverUtils not working with pixelmon 9.1.10 or 9.1.11

### ISSUE THREAD

**Issue by theonlytruegod** [CloverCard/CloverTrainerUtils#7]
When I initiate a battle even from a fresh install of clovertrainerutils I get this error and the battle does not start. It spawns an invisible trainer npc without starting.

Server thread/INFO13:06:13
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: java.lang.NullPointerException
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.battles.controller.participants.PlayerParticipant.<init>(PlayerParticipant.java:147)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.clovercard.clovertrainerutils.helpers.shuffler.ShufflerHelper.startTrainerBattle(ShufflerHelper.java:117)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.clovercard.clovertrainerutils.listeners.BattleListeners.createClone(BattleListeners.java:228)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.clovercard.clovertrainerutils.listeners.BattleListeners.onBattleStarted(BattleListeners.java:111)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraftforge.eventbus.ASMEventHandler_15_BattleListeners_onBattleStarted_Pre.invoke(.dynamic)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.battles.BattleRegistry.performPreBattleChecksAndEvents(BattleRegistry.java:70)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.battles.BattleRegistry.startBattle(BattleRegistry.java:49)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity.startBattle(AbstractBattleEntity.java:134)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70227_a(OccupiedPokeBallEntity.java:343)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.entity.projectile.ThrowableEntity.redirect$zmf000$arclight$projectileHit(ThrowableEntityMixin.java:526)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntityMixin.java:67)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.entities.pokeballs.PokeBallEntity.func_70071_h_(PokeBallEntity.java:227)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at com.pixelmonmod.pixelmon.entities.pokeballs.OccupiedPokeBallEntity.func_70071_h_(OccupiedPokeBallEntity.java:132)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorldMixin.java:612)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.world.World.func_217390_a(WorldMixin.java:554)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorldMixin.java:405)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServerMixin.java:851)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:291)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232)
[com.pixelmonmod.pixelmon.entities.pixelmon.AbstractBattleEntity:startBattle:136]: at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by theonlytruegod** [comment]
I found a fix by deleting the trainer and re creating it. Not sure why this issue happened.

**Comment by CloverCard** [comment]
Newest build runs on 9.1.11, hopefully resolves any lingering issues.
